### PR TITLE
Reorganize test_bash_actions.py

### PR DESCRIPTION
**Pull request by joannfeng**

### CODE REVIEW

**Comment by BoPeng** [comment]
Please

1. Move the test out of the class. 
2. Remove the class and the bottom `__main__` part.

**Comment by BoPeng** [comment]
You also need to remove `class TestActions(unittest.TestCase):` since it is no longer needed.

**Comment by BoPeng** [comment]
Now, install a tool called `pyflakes` (`pip install pyflakes`) and then run 

```
pyflakes test/test_actions.py
```
and fix the file according to the warnings.

Then install `isort`, and run it over the file. `isort` will sort the imports.

Then install `yapf`, and run

```
yapf -i --style "{based_on_style: chromium, indent_width: 4}" test/test_actions.py
```
which will format the file...

These are tools to keep source files clean and in consistent style.

**Comment by BoPeng** [comment]
Note that you can set `yapf` as your default formatter in VS Code. You will need to set `{based_on_style: chromium, indent_width: 4}` as `Python > Formatting: Yapf Args` to apply the same style to all files.

**Comment by joannfeng** [comment]
some of the warnings are about how the variable 'script' is unused. The tests previously did not come with assert statements that used this variable. Is it enough to remove the script variable assignment and just have execute_workflow, or are there assert statements I should be testing?

**Comment by BoPeng** [comment]
Yes, remove the assignment if the assigned variable is unused.

**Comment by BoPeng** [comment]
Some tests are good enough to have a single `execute_workflow` call because they meant to test if SoS can handle them without raising an error.

**Comment by joannfeng** [comment]
Okay, I ran both test_actions.py and test_bash_actions.py through pyflakes, isort, and yapf.

**Comment by BoPeng** [comment]
Thanks. You could write a small script to do all these, although fixing warnings have to be done manually.

**Pull request merged**
