### PR TITLE
specify config file name for pylint 

### PR DESCRIPTION
**Pull request by he1l0world**

### CODE REVIEW

**Comment by BoPeng** [comment]
There are many warning/errors (https://github.com/vatlab/sos/runs/2926071452?check_suite_focus=true) but pylint workflow still passes. There is something wrong here.

**Comment by he1l0world** [comment]
I saw after adding the config file many of the warnings are ignored, we can always add more to ignore to the config file

**Comment by he1l0world** [comment]
I can also add more rules to the ".python-lint" file to ignore some of the non-essential warnings.

**Comment by BoPeng** [comment]
Yes, let us get pylink passing before making the config more stringent later.

**Comment by he1l0world** [comment]
I have two proposals, 1. We can disable the pylint for some of the files to get rid of the warnings. 2. Change some of the restrictions such as setting "max-nested-blocks" to 10. 
Which way you think is better or is there any other way you want to solve it.

**Comment by BoPeng** [comment]
I prefer changing the configuration because these files could have other problems.

**Comment by he1l0world** [comment]
Sounds good, and I will start working on it.

**Comment by BoPeng** [comment]
I am using vscode, which is IMHO best among atom, pycharm etc. I have not figured out how to jump to particular locations from pylint output but it would be worthwhile to go through the vscode settings to understand how it integrates with pylint.

**Comment by he1l0world** [comment]
Ok sounds good.

**Comment by he1l0world** [comment]
This is what I have in VS code settings.json file:
{
    "python.linting.pylintEnabled": true,
    "python.linting.enabled": true,
    "python.linting.pylintArgs": ["--rcfile", ".github/linters/.python-lint"]
}
And after we save the python file it will automatically run the pylint for that file, and we will be able to see the warning. Correct me if I'm wrong

**Comment by BoPeng** [comment]
Allow the specification of `.rc` file is the first step since I often ignore linting warnings since there are too many. The second problem is that when I am in the linting output, clicking the warning, the editor cannot go to the relevant line.

I know the editor has linting warnings marked, but it is easier to go from the linting output, which allows me to fix one type of the problem at a time.

**Comment by he1l0world** [comment]
I'm not sure if there's a feature that allows jumping to the relevant line by clicking the lining output but I'm working on the first issue to ignore the warning

**Comment by BoPeng** [comment]
I tried again today and clicking the linting output can move my cursor to the line. This is after VS Code asked me to upgrade.

**Comment by he1l0world** [comment]
Here's a warning about "src/sos/docker/client.py:161:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)", should I also ignore this? I feel this could be a nontrivial report.

**Comment by he1l0world** [comment]
Some of the warnings can be fixed in the source file, for example, "R1724: Unnecessary "elif" after "continue" (no-else-continue)" , "R1705: Unnecessary "elif" after "return" (no-else-return)" and "standard import "from contextlib import redirect_stdout, redirect_stderr" should be placed before "import zmq" (wrong-import-order)" etc. Do you want me to ignore them or fix them in those source file?  I ingored some of the trivial warnings and here is the result of pylint: https://github.com/he1l0world/sos/actions/runs/1053878849

**Comment by BoPeng** [comment]
For the trivial ones, yes, please fix. For the if/elif/return ones, changing the code without knowing what is going on could lead to errors, so let us add the warning to the ignored list for now.

**Comment by he1l0world** [comment]
Sounds good, I will make a list of trivial ones to fix and leave the rest to ignore. I will post the list later here for you to review after that I will go ahead to fix them.

**Comment by BoPeng** [comment]
I would add all warnings to the config file so that the github action will pass. Then we can remove the item one by one so that we can create commits that pass the CI each time.

**Comment by he1l0world** [comment]
Ok that also works

**Comment by he1l0world** [comment]
Right now I ignored all the warnings but here's one last issue "sos/misc/spyder/spyder_kernel.py has relative import with too many levels". Details can be found in here: https://github.com/he1l0world/sos/runs/3131639709?check_suite_focus=true

I haven't found a workaround for this so my proposal is to ignore that file.

**Pull request closed without merging**
