### PR TITLE
Issue1542

### PR DESCRIPTION
**Pull request by BoPeng**
#1542 

It looks like python 3.12 changes the calling pattern for multiple inheritance.

### CODE REVIEW

**Comment by gaow** [comment]
3.9 now failed the tests? It is insane how Python is updated so frequently and have all these compatibility issues! *Even* R does not do this to its users.

**Comment by BoPeng** [comment]
Yes, got python 3.10, 3.11, and 3.12 working, but 3.9 fails. The problem is that I used some private functions of `pathlib` in order to subclass `pathlib.Path`, and things got broken when this library was updated.

Let me see what is going on with 3.9.

**Comment by BoPeng** [comment]
The problem with python 3.9 is related to remote execution of tasks, which is quite puzzling, I do not have time to further investigate this issue and will leave it for later. You can make use of this branch if you are in a hurry.

**Comment by gaow** [comment]
Thank you @BoPeng . We typically use `conda` distributed packages to setup our containers automatically but for now we can try to install from this branch.

**Comment by gaow** [comment]
@BoPeng another idea is that we drop support ot python 3.9 and lower. We require it 3.10 and up?

**Pull request merged**
